import { db } from "./db";
import { droneScans, alerts } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingScans = await db.select().from(droneScans).limit(1);
  if (existingScans.length > 0) return;

  const scanData = [
    {
      scanName: "SF Bay North Sweep",
      location: "San Francisco Bay, North",
      latitude: 37.8199,
      longitude: -122.4783,
      algaeLevel: 23.5,
      greeneryIndex: 0.72,
      waterQuality: 85.0,
      temperature: 14.2,
      phLevel: 8.1,
      dissolvedOxygen: 7.8,
      turbidity: 12.3,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "Healthy conditions. Minor kelp presence detected along northern shoreline.",
    },
    {
      scanName: "Half Moon Bay Survey",
      location: "Half Moon Bay, CA",
      latitude: 37.4636,
      longitude: -122.4286,
      algaeLevel: 67.8,
      greeneryIndex: 0.35,
      waterQuality: 42.0,
      temperature: 16.1,
      phLevel: 7.4,
      dissolvedOxygen: 4.2,
      turbidity: 45.6,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "High algae concentration detected. Possible harmful bloom developing. Recommend follow-up in 48hrs.",
    },
    {
      scanName: "Pacifica Coastal Scan",
      location: "Pacifica, CA",
      latitude: 37.6138,
      longitude: -122.4869,
      algaeLevel: 12.1,
      greeneryIndex: 0.81,
      waterQuality: 91.0,
      temperature: 13.8,
      phLevel: 8.3,
      dissolvedOxygen: 8.5,
      turbidity: 8.7,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "Excellent water quality. Rich marine vegetation observed.",
    },
    {
      scanName: "Oakland Estuary Monitor",
      location: "Oakland Estuary, CA",
      latitude: 37.7952,
      longitude: -122.2542,
      algaeLevel: 45.2,
      greeneryIndex: 0.48,
      waterQuality: 58.0,
      temperature: 15.5,
      phLevel: 7.6,
      dissolvedOxygen: 5.9,
      turbidity: 28.4,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "Moderate algae levels. Turbidity elevated near industrial discharge point.",
    },
    {
      scanName: "Marin Headlands Offshore",
      location: "Marin Headlands, CA",
      latitude: 37.8270,
      longitude: -122.4994,
      algaeLevel: 8.3,
      greeneryIndex: 0.88,
      waterQuality: 94.0,
      temperature: 12.9,
      phLevel: 8.2,
      dissolvedOxygen: 9.1,
      turbidity: 5.2,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "Pristine conditions. Strong kelp forest growth observed.",
    },
    {
      scanName: "Treasure Island Perimeter",
      location: "Treasure Island, SF",
      latitude: 37.8235,
      longitude: -122.3701,
      algaeLevel: 38.9,
      greeneryIndex: 0.55,
      waterQuality: 63.0,
      temperature: 15.0,
      phLevel: 7.8,
      dissolvedOxygen: 6.3,
      turbidity: 22.1,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "Algae levels rising compared to previous month. Monitoring recommended.",
    },
    {
      scanName: "Stinson Beach Deep Scan",
      location: "Stinson Beach, CA",
      latitude: 37.8980,
      longitude: -122.6366,
      algaeLevel: 5.7,
      greeneryIndex: 0.92,
      waterQuality: 97.0,
      temperature: 13.1,
      phLevel: 8.4,
      dissolvedOxygen: 9.5,
      turbidity: 3.8,
      status: "completed",
      imageUrl: "/images/algae-map.png",
      notes: "Outstanding water quality. Diverse marine life detected.",
    },
  ];

  const insertedScans = await db.insert(droneScans).values(scanData).returning();

  const alertData = [
    {
      scanId: insertedScans[1].id,
      type: "Harmful Algal Bloom",
      severity: "critical",
      message: "Algae concentration at Half Moon Bay has exceeded 60% threshold. Cyanobacteria signatures detected. Immediate assessment recommended.",
      resolved: false,
    },
    {
      scanId: insertedScans[3].id,
      type: "Elevated Turbidity",
      severity: "warning",
      message: "Turbidity levels near Oakland Estuary industrial zone are 3x above baseline. Possible sediment runoff or discharge event.",
      resolved: false,
    },
    {
      scanId: insertedScans[5].id,
      type: "Rising Algae Trend",
      severity: "warning",
      message: "Treasure Island algae levels have increased 15% month-over-month. Approaching warning threshold.",
      resolved: false,
    },
    {
      scanId: insertedScans[1].id,
      type: "Low Dissolved Oxygen",
      severity: "critical",
      message: "Dissolved oxygen at Half Moon Bay dropped to 4.2 mg/L. Marine life at risk in affected zone.",
      resolved: false,
    },
    {
      scanId: insertedScans[0].id,
      type: "Routine Check Complete",
      severity: "info",
      message: "SF Bay North sweep completed successfully. All parameters within normal range.",
      resolved: true,
    },
  ];

  await db.insert(alerts).values(alertData);
}
